language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .
  - pip install coverage
  - pip install coveralls
script: coverage run --source=sophiabus230 setup.py test
after_success:
  - coveralls